export const DISPLAY_ALL_DRAGONS = ' DISPLAY_DRAGONS';
export const RESERVE_DRAGON = ' RESERVE_DRAGON';
export const DISPLAY_ALL_ROCKETS = 'DISPLAY_ROCKETS';
export const RESERVE_ROCKET = 'RESERVE_ROCKETS';
export const CANCEL_RESERVED_ROCKET = 'CANCEL_ROCKET';
