export const DISPLAY_ALL_DRAGONS = ' DISPLAY_DRAGONS';
export const RESERVE_DRAGON = ' RESERVE_DRAGON';
export const ROCKETS_RETRIEVED = 'ROCKETS_RETRIEVED';
export const RESERVE_ROCKET = 'RESERVE_ROCKETS';
export const CANCEL_RESERVED_ROCKET = 'CANCEL_ROCKET';
export const STARTED_FETCHING_ROCKETS = 'START_FETCHING_ROCKETS';
export const ROCKETS_FETCHED = 'ROCKETS_FETCHED';
export const ERROR_FETCHING_ROCKETS = 'ERROR_FETCHING_ROCKETS';
