export const DISPLAY_ALL_DRAGONS = ' DISPLAY_DRAGONS';
export const RESERVE_DRAGON = ' RESERVE_DRAGON';
export const MISSIONS_RETRIEVED = 'MISSIONS_RETRIEVED';
export const MISSIONS_FETCH_STARTED = 'MISSIONS_FETCH_STARTED';
export const MISSIONS_FETCH_FAILED = 'MISSIONS_FETCH_FAILED';
